version: 2
jobs:
  deploy_prod: # ジョブ名
    docker:
      - image: circleci/node:10.7 # ジョブ実行環境のDockerイメージを記述
    steps:
      - checkout # ソースコードのチェックアウト
      - run: # 順に実行したいコマンドとコマンドに名前をつけます
          name: yarn install
          command: yarn install
      - run:   
          name: Install Firebase-tools
          command: yarn global add firebase-tools
      - run:   
          name: Install processmd
          command: yarn global add processmd --dev
      - run:
          name: delete json 
          command: rm -rf contents/summary.json; rm -rf contents/json/*
      - run:
          name: md to json
          command: yarn processmd "contents/markdown/**/*.md" --preview 160 --stdout --outputDir contents/json > contents/summary.json
      - run:
          name: build
          command: yarn nuxt generate
      - run:
          name: deploy to Firebase Hosting
          command: yarn firebase deploy production hal-tech-club --project "$FIREBASE_PROJECT_ID" --token=$FIREBASE_TOKEN # プロジェクト上のfirebase-toolsでデプロイします

  deploy_dev: # ジョブ名
    docker:
      - image: circleci/node:10.7 # ジョブ実行環境のDockerイメージを記述
    steps:
      - checkout # ソースコードのチェックアウト
      - run: # 順に実行したいコマンドとコマンドに名前をつけます
          name: yarn install
          command: yarn install
      - run:   
          name: Install Firebase-tools
          command: yarn global add firebase-tools
      - run:   
          name: Install processmd
          command: yarn global add processmd --dev
      - run:
          name: delete json 
          command: rm -rf contents/summary.json; rm -rf contents/json/*
      - run:
          name: md to json
          command: yarn processmd "contents/markdown/**/*.md" --preview 160 --stdout --outputDir contents/json > contents/summary.json
      - run:
          name: build
          command: yarn nuxt generate
      - run:
          name: deploy to Firebase Hosting
          command: yarn firebase deploy develop develop-hal-tech-club --project "$FIREBASE_PROJECT_ID" --token=$FIREBASE_TOKEN # プロジェクト上のfirebase-toolsでデプロイします

workflows:
  version: 2
  deploy: # ワークフローの名前
    jobs:
      - deploy_prod: # 上で定義したジョブを指定します
          filters:
            branches:
              only: master # masterブランチのみを実行対象とします
      - deploy_dev: # 上で定義したジョブを指定します
          filters:
            branches:
              only: develop # developブランチのみを実行対象とします
  
